package lt.vu.mybatis.dao;

import java.util.List;
import lt.vu.mybatis.model.PostTag;

public interface PostTagMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.POST_TAG
     *
     * @mbg.generated Sun May 02 16:54:16 EEST 2021
     */
    int insert(PostTag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.POST_TAG
     *
     * @mbg.generated Sun May 02 16:54:16 EEST 2021
     */
    List<PostTag> selectAll();
}