package lt.vu.mybatis.dao;

import java.util.List;
import lt.vu.mybatis.model.Post;
import org.mybatis.cdi.Mapper;

@Mapper
public interface PostMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.POST
     *
     * @mbg.generated Sun May 02 16:54:16 EEST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.POST
     *
     * @mbg.generated Sun May 02 16:54:16 EEST 2021
     */
    int insert(Post record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.POST
     *
     * @mbg.generated Sun May 02 16:54:16 EEST 2021
     */
    Post selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.POST
     *
     * @mbg.generated Sun May 02 16:54:16 EEST 2021
     */
    List<Post> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.POST
     *
     * @mbg.generated Sun May 02 16:54:16 EEST 2021
     */
    int updateByPrimaryKey(Post record);
}