package lt.vu.mybatis.dao;

import java.util.List;
import lt.vu.mybatis.model.Tag;
import org.mybatis.cdi.Mapper;

@Mapper
public interface TagMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.TAG
     *
     * @mbg.generated Sun May 02 16:54:16 EEST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.TAG
     *
     * @mbg.generated Sun May 02 16:54:16 EEST 2021
     */
    int insert(Tag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.TAG
     *
     * @mbg.generated Sun May 02 16:54:16 EEST 2021
     */
    Tag selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.TAG
     *
     * @mbg.generated Sun May 02 16:54:16 EEST 2021
     */
    List<Tag> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.TAG
     *
     * @mbg.generated Sun May 02 16:54:16 EEST 2021
     */
    int updateByPrimaryKey(Tag record);
}