package lt.vu.mybatis.model;

import java.util.Date;

public class Author {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.AUTHOR.ID
     *
     * @mbg.generated Sun May 02 16:54:16 EEST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.AUTHOR.USERNAME
     *
     * @mbg.generated Sun May 02 16:54:16 EEST 2021
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.AUTHOR.DATE_JOINED
     *
     * @mbg.generated Sun May 02 16:54:16 EEST 2021
     */
    private Date dateJoined;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.AUTHOR.ID
     *
     * @return the value of PUBLIC.AUTHOR.ID
     *
     * @mbg.generated Sun May 02 16:54:16 EEST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.AUTHOR.ID
     *
     * @param id the value for PUBLIC.AUTHOR.ID
     *
     * @mbg.generated Sun May 02 16:54:16 EEST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.AUTHOR.USERNAME
     *
     * @return the value of PUBLIC.AUTHOR.USERNAME
     *
     * @mbg.generated Sun May 02 16:54:16 EEST 2021
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.AUTHOR.USERNAME
     *
     * @param username the value for PUBLIC.AUTHOR.USERNAME
     *
     * @mbg.generated Sun May 02 16:54:16 EEST 2021
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.AUTHOR.DATE_JOINED
     *
     * @return the value of PUBLIC.AUTHOR.DATE_JOINED
     *
     * @mbg.generated Sun May 02 16:54:16 EEST 2021
     */
    public Date getDateJoined() {
        return dateJoined;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.AUTHOR.DATE_JOINED
     *
     * @param dateJoined the value for PUBLIC.AUTHOR.DATE_JOINED
     *
     * @mbg.generated Sun May 02 16:54:16 EEST 2021
     */
    public void setDateJoined(Date dateJoined) {
        this.dateJoined = dateJoined;
    }
}