package lt.vu.mybatis.model;

public class PostTag {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.POST_TAG.POST_ID
     *
     * @mbg.generated Sun May 02 16:54:16 EEST 2021
     */
    private Integer postId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.POST_TAG.TAG_ID
     *
     * @mbg.generated Sun May 02 16:54:16 EEST 2021
     */
    private Integer tagId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.POST_TAG.POST_ID
     *
     * @return the value of PUBLIC.POST_TAG.POST_ID
     *
     * @mbg.generated Sun May 02 16:54:16 EEST 2021
     */
    public Integer getPostId() {
        return postId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.POST_TAG.POST_ID
     *
     * @param postId the value for PUBLIC.POST_TAG.POST_ID
     *
     * @mbg.generated Sun May 02 16:54:16 EEST 2021
     */
    public void setPostId(Integer postId) {
        this.postId = postId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.POST_TAG.TAG_ID
     *
     * @return the value of PUBLIC.POST_TAG.TAG_ID
     *
     * @mbg.generated Sun May 02 16:54:16 EEST 2021
     */
    public Integer getTagId() {
        return tagId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.POST_TAG.TAG_ID
     *
     * @param tagId the value for PUBLIC.POST_TAG.TAG_ID
     *
     * @mbg.generated Sun May 02 16:54:16 EEST 2021
     */
    public void setTagId(Integer tagId) {
        this.tagId = tagId;
    }
}