package lt.vu.mybatis.model;

import java.util.Date;

public class Post {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.POST.ID
     *
     * @mbg.generated Sun May 02 16:54:16 EEST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.POST.TITLE
     *
     * @mbg.generated Sun May 02 16:54:16 EEST 2021
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.POST.BODY
     *
     * @mbg.generated Sun May 02 16:54:16 EEST 2021
     */
    private String body;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.POST.AUTHOR_ID
     *
     * @mbg.generated Sun May 02 16:54:16 EEST 2021
     */
    private Integer authorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.POST.DATE
     *
     * @mbg.generated Sun May 02 16:54:16 EEST 2021
     */
    private Date date;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.POST.ID
     *
     * @return the value of PUBLIC.POST.ID
     *
     * @mbg.generated Sun May 02 16:54:16 EEST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.POST.ID
     *
     * @param id the value for PUBLIC.POST.ID
     *
     * @mbg.generated Sun May 02 16:54:16 EEST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.POST.TITLE
     *
     * @return the value of PUBLIC.POST.TITLE
     *
     * @mbg.generated Sun May 02 16:54:16 EEST 2021
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.POST.TITLE
     *
     * @param title the value for PUBLIC.POST.TITLE
     *
     * @mbg.generated Sun May 02 16:54:16 EEST 2021
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.POST.BODY
     *
     * @return the value of PUBLIC.POST.BODY
     *
     * @mbg.generated Sun May 02 16:54:16 EEST 2021
     */
    public String getBody() {
        return body;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.POST.BODY
     *
     * @param body the value for PUBLIC.POST.BODY
     *
     * @mbg.generated Sun May 02 16:54:16 EEST 2021
     */
    public void setBody(String body) {
        this.body = body;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.POST.AUTHOR_ID
     *
     * @return the value of PUBLIC.POST.AUTHOR_ID
     *
     * @mbg.generated Sun May 02 16:54:16 EEST 2021
     */
    public Integer getAuthorId() {
        return authorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.POST.AUTHOR_ID
     *
     * @param authorId the value for PUBLIC.POST.AUTHOR_ID
     *
     * @mbg.generated Sun May 02 16:54:16 EEST 2021
     */
    public void setAuthorId(Integer authorId) {
        this.authorId = authorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.POST.DATE
     *
     * @return the value of PUBLIC.POST.DATE
     *
     * @mbg.generated Sun May 02 16:54:16 EEST 2021
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.POST.DATE
     *
     * @param date the value for PUBLIC.POST.DATE
     *
     * @mbg.generated Sun May 02 16:54:16 EEST 2021
     */
    public void setDate(Date date) {
        this.date = date;
    }
}